### ISSUE TITLE
Explain motivation for cert-gen.sh

### ISSUE THREAD

**Issue by blbradley** [saltstack-formulas/vault-formula#1]
I am unsure of the usage of this 'child' cert.

In addition, I imagine you're setting up the keystore for some kind of Java app. I've got some Kafka specific Salt states that create a keystore that I'd be willing to share. We can remove that part of the script when you are ready. Correct?

**Comment by myoung34** [comment]
That's fine with me, `cert-gen.sh` is just a file I had handy that generates self-signed certs generically. As far as vault is concerned it just needs to point to a valid crt and pem

**Comment by blbradley** [comment]
Great!

Is a 'child' cert generated for distribution to the clients of whatever you pulled this from?

**Comment by myoung34** [comment]
it would be iirc

**Comment by blbradley** [comment]
Excellent. That's all I needed. Thanks!
