### ISSUE TITLE
systemd service not enabled

### ISSUE THREAD

**Issue by mruepp** [saltstack-formulas/vault-formula#19]
To enable the systemd service as defined in the server.sls, the vault_systemd.service.jinja needs to contain the following section:
[Install]
WantedBy=multi-user.target

**Comment by n-rodriguez** [comment]
H there! can we close this issue?

**Comment by dafyddj** [comment]
Yes, this should have been closed with #22.

**Comment by n-rodriguez** [comment]
Ok, thank you!
