### ISSUE TITLE
Modify repo settings to be consistent with other repos in this org

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/vault-formula#45]
As mentioned in https://github.com/saltstack-formulas/vault-formula/pull/44#issue-320385210, certain cross-formula automation isn't possible due to the repo's settings.  Opening this issue here to discuss if there are any issues with getting the settings modified to match the other formulas.

**Comment by dafyddj** [comment]
FWIW I don't see an issue with bringing this repo into line with the other formulas.

**Comment by myii** [comment]
The important setting (blocking automation) has been resolved so closing this issue:

* https://freenode.logbot.info/saltstack-formulas/20191007#c2733816
* https://freenode.logbot.info/saltstack-formulas/20191007#c2733875
